public with sharing class dealerCallout {
	public dealerCallout() {
		
	}

	public static String sampleDataMethod(){

		return '{"result": [{"name": "Kun Hyundai Purasaivakkam","make": "8","addressDetails": [{"id": "","address": "No 7,Gangadeewarar Koil ST,Purasawakkam","city": "Chennai","make": "8","email": "kunrajeshm@gmail.com","phone": "9167014403","pincode": "600084","state": "Tamil Nadu"}]}}';
	}
}