global class FetchNeftDDresponsewrapper{


public String bpms_error_code;
public String bpms_error_msg;
public out_msg_cls out_msg;

public class  out_msg_cls{

public string Transation_Amount;
public String Beneficiary_Cust_Name;
public String Narration;
public String Mode_Of_Payment;
public String Tran_Ref_Num;
public String Transaction_Date;
public String HttpStatus;
public String ErrorCode;
public String ErrorMessage;


}

}