public class GetBankStatements{
	public cls_payload payload;
	public class cls_payload {
		public String loanDuration;	//6
		public String loanAmount;	//100000
		public String loanType;	//Personal
		public String bankName;	//Karur Vysya Bank
		public String facilityId;	//MTUzPRg0K
		public String facility;	//NONE
		public String base64File;	//abcd
		public String appFolderId;	//a4L0l0000006btE
		public String yearMonthFrom;	//2017-04
		public String yearMonthTo;	//2018-03
		public String password;	//5803747
		public String fileName;	//1219135000000845 _ 01-APR-2017_03-APR-2018.pdf
		public String contentType;	//application/pdf
		public String applicationType;	//1
		public String applicationId;	//a4V0l0000004dZ0
		public String customerId;	//
		public String documentType;	//abc
		public String accountNumbers;	//1
		public String uuid;	//
		public String isScannedStatement;	//false
	}
	
}