public class HL_Execution_Certifi_C11Req {
    
    public String exe_tenantId= 'cuecent_tenant';   //cuecent_tenant
    public String owner_tenantId= 'cuecent_tenant'; //cuecent_tenant
    public String serviceName= 'TestJsonStr';   //TestJsonStr
    public cls_inputVariables inputVariables;
    public class cls_inputVariables {        
        public String in_msg= '';   //
        public String unique_key= '';   //
        public String pdf_unique_key= '';
        public cls_inputmap inputmap;
    }
    
     public class cls_inputmap {
        public string Borrower1_Add_line1='';
        public string Borrower5_Names    ='';
        public string Borrower5_eSign    ='';
        public string Borrower1_Names    ='';
        public string Borrower3_Add_line1='';
        public string Borrower4_Add_line3='';
        public string Loc_Ref_Branch     ='';
        public string Borrower3_Add_line3='';
        public string Borrower3_Add_line2='';
        public string Guarantor4_eSign   ='';
        public string Borrower1_Name1    ='';
        public string Borrower4_Add_line2='';
        public string Borrower4_Add_line1='';
        public string Borrower4_Names    ='';
        public string Date_Time_Ver      ='';
        public string Guarantor1_eSign   ='';
        public string Date_Time_Adm      ='';
        public string Guarantor2_Names   ='';
        public string Borrower4_eSign    ='';
        public string Sanction_date      ='';
        public string Borrower4_Name1    ='';
        public string Borrower1_Add_line3='';
        public string Borrower1_Add_line2='';
        public string Borrower2_eSign    ='';
        public string Borrower3_eSign    ='';
        public string Guarantor5_eSign   ='';
        public string Sanction_Ref_Number='';
        public string Borrower2_Names    ='';
        public string Guarantor3_eSign   ='';
        public string Guarantor2_eSign   ='';
        public string Guarantor4_Names   ='';
        public string Doc_gen_date       ='';
        public string Guarantor5_Names   ='';
        public string Borrower2_Name1    ='';
        public string Guarantor3_Names   ='';
        public string Guarantor1_Names   ='';
        public string Borrower3_Name1    ='';
        public string Borrower2_Add_line1='';
        public string Borrower3_Names    ='';
        public string Borrower2_Add_line2='';
        public string Borrower2_Add_line3='';
        public string Borrower1_eSign    ='';
        public string  Guarantor6_Names         ='';
        public string  Guarantor7_Names         ='';
        public string  Guarantor8_Names         ='';
        public string  Guarantor9_Names         ='';
        public string  Guarantor10_Names        ='';
     }
}