public class LAP_A23D_LAFADoc {
	public String exe_tenantId= 'cuecent_tenant';   //cuecent_tenant
    public String owner_tenantId= 'cuecent_tenant'; //cuecent_tenant
    public String serviceName= 'TestJsonStr'; //TestJsonStr
    public cls_inputVariables inputVariables;
    public class cls_inputVariables {        
        public String in_msg= '';   //
        public String unique_key= '';   //
        public String pdf_unique_key= '';
        public cls_inputmap inputmap;
    }
    public class cls_inputmap {
        public string Auth_Sign_Bnk             = '';
        public string Loc_Ref_Branch 			= '';
		public string Disb_Ref_Day              = '';
		public string Disb_Ref_Month            = '';
		public string Disb_Ref_Year             = '';
		public string Borrower_Details          = '';
		public string Ap_LT                     = '';
		public string Ap_LT_inwords 			= '';
		public string Int_ROI 					= '';
		public string Variance 					= '';
		public string MCLR_Rate 				= '';
		public string Loan_Purpose 			    = '';
        public string Rating_Freq 			    = '';
        public string PreClosure_Charges 		= '';
        public string Penal_Interest 			= '';
        public string Loan_tenor                = '';
        public string EMI_amount                = '';
        public string DD_FI                     = '';
        public string DD_LI                     = '';
        public string Borrower1_Names           = '';
        public string Borrower2_Names           = '';
        public string Borrower3_Names           = '';
        public string Borrower4_Names           = '';
        public string Borrower5_Names           = '';
        //collateral details
        public string Nature_Property_1         = '';
        public string Nature_Property_2         = '';
        public string Nature_Property_3         = '';
        public string Nature_Property_4         = '';
        public string Nature_Property_5         = '';
        public string Survey_No_1              = '';
        public string Survey_No_2              = '';
        public string Survey_No_3              = '';
        public string Survey_No_4              = '';
        public string Survey_No_5              = '';
        public string Plot_Door_Bungalow_No_1   = '';
        public string Plot_Door_Bungalow_No_2   = '';
        public string Plot_Door_Bungalow_No_3   = '';
        public string Plot_Door_Bungalow_No_4   = '';
        public string Plot_Door_Bungalow_No_5   = '';
        public string Extent_Site_Uds_1         = '';
        public string Extent_Site_Uds_2         = '';
        public string Extent_Site_Uds_3         = '';
        public string Extent_Site_Uds_4         = '';
        public string Extent_Site_Uds_5         = '';
        public string Built_up_area_1           = '';
        public string Built_up_area_2           = '';
        public string Built_up_area_3           = '';
        public string Built_up_area_4           = '';
        public string Built_up_area_5           = '';
        public string Floor_No_1               = '';
        public string Floor_No_2               = '';
        public string Floor_No_3               = '';
        public string Floor_No_4               = '';
        public string Floor_No_5               = '';
        public string Ward_No_1                 = '';
        public string Ward_No_2                 = '';
        public string Ward_No_3                 = '';
        public string Ward_No_4                 = '';
        public string Ward_No_5                 = '';
        public string Building_Society_Name_No_1= '';
        public string Building_Society_Name_No_2= '';
        public string Building_Society_Name_No_3= '';
        public string Building_Society_Name_No_4= '';
        public string Building_Society_Name_No_5= '';
        public string Street_Name_1             = '';
        public string Street_Name_2             = '';
        public string Street_Name_3             = '';
        public string Street_Name_4             = '';     
        public string Street_Name_5             = '';
        public string Village_Town_1            = '';
        public string Village_Town_2            = '';
        public string Village_Town_3            = '';
        public string Village_Town_4            = '';
        public string Village_Town_5            = '';
        public string Taluka_Tehsil_1           = '';
        public string Taluka_Tehsil_2           = '';
        public string Taluka_Tehsil_3           = '';
        public string Taluka_Tehsil_4           = '';
        public string Taluka_Tehsil_5           = '';
        public string District_Name_1           = '';
        public string District_Name_2           = '';
        public string District_Name_3           = '';
        public string District_Name_4           = '';
        public string District_Name_5           = '';
        public string State_Name_1              = '';
        public string State_Name_2              = '';
        public string State_Name_3              = '';
        public string State_Name_4              = '';
        public string State_Name_5              = '';
        public string PIN_CODE_1                = '';
        public string PIN_CODE_2                = '';
        public string PIN_CODE_3                = '';
        public string PIN_CODE_4                = '';
        public string PIN_CODE_5                = '';
       
    }

}