@isTest
public class Test_CBR_DTLS_HELPER_HL {
@isTest
    public static void method1(){
        CBR_DTLS_HELPER_HL ob=new CBR_DTLS_HELPER_HL();
        ob.exe_tenantId='test';
        ob.owner_tenantId='siwwje';
        CBR_DTLS_HELPER_HL.cls_in_msg inms=new CBR_DTLS_HELPER_HL.cls_in_msg();
        inms.AccountNumber='1324122131';
        inms.Category_Of_Borrowers=889787;
        inms.CheckerID='';
    }
}