@isTest
public class Test_HLpre_Approve_Sanction_DigioDocreq {
@isTest
    public static void method1(){
        HLpre_Approve_Sanction_DigioDocreq  ob=new HLpre_Approve_Sanction_DigioDocreq ();
        HLpre_Approve_Sanction_DigioDocreq.cls_inputmap  a=new HLpre_Approve_Sanction_DigioDocreq.cls_inputmap();
        HLpre_Approve_Sanction_DigioDocreq.cls_inputVariables b=new HLpre_Approve_Sanction_DigioDocreq.cls_inputVariables();
    }
}