@isTest
public class Test_NumberToWordConversion {
@isTest
    public static void method1(){
        NumberToWordConversion ob=new NumberToWordConversion();
        ob.getNumberTOWordConvertion2(16.5);
        ob.getNumberTOWordConvertion(121.4545557);
        ob.getNumberTOWordConvertion(0);
         ob.getNumberTOWordConvertion(12.3);
         
          ob.getNumberTOWordConvertion2(2000.25588);
          
            ob.getNumberTOWordConvertion2(8598585.25588);
             ob.getNumberTOWordConvertion2(5858856.5885854656);
        
    }
    @isTest
    public static void method2(){
    NumberToWordConversion ob=new NumberToWordConversion();
    ob.getNumberTOWordConvertion2(252588);
    ob.getNumberTOWordConvertion(477777777.115555);
    
    }
     @isTest
    public static void method3(){
    NumberToWordConversion ob=new NumberToWordConversion();
    ob.getNumberTOWordConvertion2(252588.89987988978);
    ob.getNumberTOWordConvertion(999999977777777.115555);
    
    }
}