@isTest
public class Test_HL_Execution_Certifi_C11Req {
@isTest
    public static void method1(){
        HL_Execution_Certifi_C11Req ob=new HL_Execution_Certifi_C11Req();
        HL_Execution_Certifi_C11Req.cls_inputVariables inob=new HL_Execution_Certifi_C11Req.cls_inputVariables();
        HL_Execution_Certifi_C11Req.cls_inputmap inmapobj=new HL_Execution_Certifi_C11Req.cls_inputmap();
        
    }
}